version: "3.7"
services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=bucketeer
      - POSTGRES_PASSWORD=bucketeer_pass
      - POSTGRES_DB=bucketeer_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - mynetwork

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_HOST=database  
      - DB_USER=bucketeer
      - DB_PASSWORD=bucketeer_pass
      - DB_NAME=bucketeer_db
      - DB_PORT=5432
    depends_on:
      - database
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  data:
